Collections:
  - Name: CASViT
    Metadata:
      Training Data: ImageNet-1k
    Paper:
      URL: https://arxiv.org/abs/2408.03703
      Title: "CAS-ViT: Convolutional Additive Self-attention Vision Transformers for Efficient Mobile Applications"
    README: configs/casvit/README.md
    Code:
      URL: https://github.com/bear-coder-9527/BackboneHub/blob/main/mmpretrain/models/backbones/casvit.py
      Version: v0.19.0

Models:
  - Name: casvit-small_8xb256_in1k
    In Collection: CASViT
    Config: configs/casvit/casvit-small_8xb256_in1k.py
    Converted From:
      Weights: https://github.com/Tianfang-Zhang/CAS-ViT/blob/main/MODEL_ZOO.md
      Code: https://github.com/Tianfang-Zhang/CAS-ViT?tab=readme-ov-file

  - Name: casvit-xsmall_8xb256_in1k
    In Collection: CASViT
    Config: configs/casvit/casvit-xsmall_8xb256_in1k.py
    Converted From:
      Weights: https://github.com/Tianfang-Zhang/CAS-ViT/blob/main/MODEL_ZOO.md
      Code: https://github.com/Tianfang-Zhang/CAS-ViT?tab=readme-ov-file

  - Name: casvit-tiny_8xb256_in1k
    In Collection: CASViT
    Config: configs/casvit/casvit-tiny_8xb256_in1k
    Converted From:
      Weights: https://github.com/Tianfang-Zhang/CAS-ViT/blob/main/MODEL_ZOO.md
      Code: https://github.com/Tianfang-Zhang/CAS-ViT?tab=readme-ov-file

  - Name: casvit-middle_8xb256_in1k
    In Collection: CASViT
    Config: configs/casvit/casvit-middle_8xb256_in1k.py
    Converted From:
      Weights: https://github.com/Tianfang-Zhang/CAS-ViT/blob/main/MODEL_ZOO.md
      Code: https://github.com/Tianfang-Zhang/CAS-ViT?tab=readme-ov-file


